name: Helm Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Lint and Test Charts
    types:
      - completed
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on:
      group: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Helm Release
        uses: IMIO/gha/helm-release-notify@v3.9.2
        with:
          TARGET_DIR: plausible-analytics
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HELM_DEPENDENCIES: bitnami,https://charts.bitnami.com/bitnami
